
STATUS_OK = 0
STATUS_CRITICAL = 1
STATUS_WARNING = 2
STATUS_UNKNOWN = 3
STATUS_PENDING = 4
STATUS_UNDETERMINED = 255 # we couldn't figure out what the status is

STATE_SOFT = 0
STATE_HARD = 1
STATE_UNKNOWN = 255

CHECK_TYPE_ACTIVE = 0
CHECK_TYPE_PASSIVE = 1
